# trans_config.yaml

data:
  train_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/train"
  val_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/train"
  eval_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/val"
  height: 256
  width: 256

cuda_visible_devices: "0"

workdir:
  weights_path: "./work-dir/checkpoint_transweather_debug"
  save_img_path: "./work-dir/checkpoint_transweather_debug/imgs"
  log_path: "./work-dir/checkpoint_transweather_debug/log"

model:
  type: "transweather_base"
  whether_pretrain: False
  load_checkpoint_path: "./work-dir/checkpoint_transweather"

training:
  device: "cuda"  # "cuda" if torch.cuda.is_available() else "cpu"
  epoch: 300
  batch_size: 128
  learning_rate: 0.0002
  momentum: 0.1
  loss_type: "MSE"

evaluation:
  interval: 3

optimizer:
  type: Adam
