# trans_config.yaml

data:
  train_dir: "/share/home/dq070/hy-tmp/AS_id_all/rain/rain-img/img/train"
  val_dir: "/share/home/dq070/hy-tmp/AS_id_all/rain/imd/img"
  eval_dir: "/share/home/dq070/hy-tmp/AS_id_all/rain/imd/img"
  height: 224
  width: 224

cuda_visible_devices: "0,1,2,3"

workdir:
  weights_path: "./checkpoint_transweather"
  save_img_path: "./checkpoint_transweather/imgs"

model:
  type: "transweather"
  whether_pretrain: False
  load_checkpoint_path: "./checkpoint_transweather"

training:
  device: "cuda"  # "cuda" if torch.cuda.is_available() else "cpu"
  epoch: 100
  batch_size: 64
  learning_rate: 2e-4
  momentum: 0.1
  loss_type: "Perceptual"

evaluation:
  interval: 3

optimizer:
  type: Adam
