# trans_config.yaml

data:
  train_dir: "/share/home/dq070/hy-tmp/datasets/cityscapes/leftImg8bit/train-all-bright0.5"
  val_dir: "/share/home/dq070/hy-tmp/datasets/cityscapes/leftImg8bit/train-all"
  eval_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/val"
  height: 224
  width: 224

cuda_visible_devices: "0,1,2,3"

workdir:
  weights_path: "./checkpoint_transweather_debug"
  save_img_path: "./checkpoint_transweather_debug/imgs"
  log_path: "./checkpoint_transweather_debug/log"

model:
  type: "transweather"
  whether_pretrain: False
  load_checkpoint_path: "./checkpoint_transweather"

training:
  device: "cuda"  # "cuda" if torch.cuda.is_available() else "cpu"
  epoch: 300
  batch_size: 1
  learning_rate: 2e-4
  momentum: 0.1
  loss_type: "Perceptual"

evaluation:
  interval: 3

optimizer:
  type: Adam
