# vss_config.yaml

data:
  train_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/train"
  val_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/train"
  eval_dir: "/share/home/dq070/Real-Time/cityscapes/leftImg8bit_sequence/val"
  height: 224
  width: 224

cuda_visible_devices: "0,1,2,3"

workdir:
  weights_path: "./checkpoint_vss/mlp.params"
  save_img_path: "./checkpoint_vss/imgs/loss_fig"
model:
  type: "resnet"
  whether_pretrain: False
  load_checkpoint_path: "./checkpoint_vss"

training:
  device: "cuda"  # "cuda" if torch.cuda.is_available() else "cpu"
  epoch: 100
  batch_size: 64
  learning_rate: 6e-05
  momentum: 0.1
  loss_type: "MSE"

evaluation:
  interval: 5

optimizer:
  type: SGD